INSERT INTO tags VALUES ('java'),
                        ('javascript'),
                        ('c#'),
                        ('react'),
                        ('html'),
                        ('css'),
                        ('spring'),
                        ('sql'),
                        ('c++'),
                        ('python'),
                        ('django'),
                        ('flask'),
                        ('php'),
                        ('wordpress'),
                        ('embedded'),
                        ('backend'),
                        ('frontend'),
                        ('desktop');
